[build]
command = "go get -u -v github.com/netlify/godoc-static && PATH=$GOPATH/bin:$PATH godoc-static -mod $GO_IMPORT_PATH -path ."
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/netlify/netlify-commons"
