[build]
command = "go get -u -v github.com/netlify/godoc-static && ls -la /opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin"
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/netlify/netlify-commons"
