[build]
command = "go get -u -v github.com/netlify/godoc-static && export PATH=$GOPATH/bin:$PATH && go env && ls -la $GOPATH/bin && godoc-static -mod $GO_IMPORT_PATH -path ."
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/netlify/netlify-commons"
